<div class="form-group ">
    <label for="intent" class="not-empty required"><i class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" data-original-title="Informe um título breve do que será abordado nesse diálogo"></i> Título da intenção</label>
    <input name="intent" id="intent" value="<?php echo isset($this->params['oIntent']) ? $this->params['oIntent']->getIntent() : '';?>" class="form-control" placeholder="" style="" required="required" title="" type="hidden">
    <input name="intent_description" id="intent_description" value="<?php echo isset($this->params['oIntent']) ? $this->params['oIntent']->getDescription() : '';?>" class="form-control" placeholder="" style="" required="required" title="" type="text">
</div>

<div class="form-group">
    <label for="examples" class="not-empty required"><i class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" data-original-title="Informe possíveis perguntas que o usuário pode fazer"></i> Quando o usuário diz: </label>
</div>

<?php
if(isset($this->params['oIntent'])) {

    foreach ($this->params['aExamples'] as $example) {
        ?>
        <div class="form-group examplesToCopy" id="examplesToCopy<?php echo isset($this->params['oIntent']) ? $this->params['oIntent']->getIntent() : '';?>">
            <input name="examples[]" id="examples" value="<?php echo $example->getText(); ?>"
                   class="form-control callClick" data-callclick-target="#copyExample<?php echo isset($this->params['oIntent']) ? $this->params['oIntent']->getIntent() : '';?>" placeholder="" style=""
                   required="required" title="" type="text">
            <a href="#" class="trash-example"><span class="glyphicon glyphicon-trash"></span></a>
        </div>
        <?php
    }
}
?>
<div class="form-group toClone" id="examplesToCopy<?php echo isset($this->params['oIntent']) ? $this->params['oIntent']->getIntent() : '';?>">
    <input name="examples[]" id="examples" value="" class="form-control callClick" data-callclick-target="#copyExample<?php echo isset($this->params['oIntent']) ? $this->params['oIntent']->getIntent() : '';?>" placeholder="" style="" required="required" title="" type="text">
    <a href="#" class="trash-example"><span class="glyphicon glyphicon-trash"></span></a>
</div>
<div id="examplesCopyDiv<?php echo isset($this->params['oIntent']) ? $this->params['oIntent']->getIntent() : '';?>"></div>

<div class="form-group">
    <button type="button" id="copyExample<?php echo isset($this->params['oIntent']) ? $this->params['oIntent']->getIntent() : '';?>" class="btn btn-info copybutton" data-copy-target="#examplesToCopy<?php echo isset($this->params['oIntent']) ? $this->params['oIntent']->getIntent() : '';?>" data-copy-to="#examplesCopyDiv<?php echo isset($this->params['oIntent']) ? $this->params['oIntent']->getIntent() : '';?>"><i class="fa fa-plus"></i> Adicionar</button>
</div>